---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/ha-card-build.yml@347d8b31df543a723027bab0dccc2b979be2c093 # master
    with:
      submodules: true
