---
name: Build

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: timmo001/workflows/.github/workflows/ha-card-build.yml@d8a1fbde67c3e0e02eb592454be2e7b78ac9deb7 # master
    with:
      submodules: true
