---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@347d8b31df543a723027bab0dccc2b979be2c093 # master
    with:
      submodules: true
    permissions:
      contents: write
