---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@d58029e7835aa103b56734cc2a82cb9ce1caf768 # master
    with:
      submodules: true
    permissions:
      contents: write
