---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@ea21189dd7dc0a122ed85d343d8b529d766e414f # master
    with:
      submodules: true
    permissions:
      contents: write
