---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@49bbe9c0795b8553b4c6cf5997406747fd42b1b7 # master
    permissions:
      pull-requests: write
      contents: write
