---
name: Renovate automerge

# yamllint disable-line rule:truthy
on:
  pull_request_target: {}

jobs:
  automerge:
    uses: timmo001/workflows/.github/workflows/renovate-automerge.yml@347d8b31df543a723027bab0dccc2b979be2c093 # master
    permissions:
      pull-requests: write
      contents: write
