---
name: HACS Validate

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    uses: timmo001/workflows/.github/workflows/ha-card-validate.yml@aa9e6d61a254018160ae491b799b36ecdf2d114d # master
    with:
      submodules: true
